Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -33,6 +33,14 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y google-chrome-stable
 
+      - name: Install ChromeDriver
+        run: |
+          CHROME_VERSION=$(google-chrome --version | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
+          wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
+          unzip chromedriver_linux64.zip
+          sudo mv chromedriver /usr/local/bin/
+          sudo chmod +x /usr/local/bin/chromedriver
+
       - name: Cache pip dependencies
         uses: actions/cache@v4
         with:
@@ -47,10 +55,13 @@ jobs:
       - name: Run tests and generate XML report
         run: |
           set -e  # Остановить выполнение при ошибке
-          pytest -v --junitxml=pytest-results.xml  # Генерация XML-отчета
+          echo "Running tests..."
+          pytest -v --junitxml=pytest-results.xml || { echo "pytest failed"; exit 1; }  # Генерация XML-отчета
+          echo "Tests completed."
 
       - name: Check for test results
         run: |
+          echo "Checking for test results..."
           if [ -f pytest-results.xml ]; then
             echo "Test results found."
           else
